package id.harissabil.mamikostvapp.ui.theme

import androidx.compose.ui.graphics.Color

val TealPrimaryLight = Color(0xFF006A64)
val TealOnPrimaryLight = Color(0xFFFFFFFF)
val TealPrimaryContainerLight = Color(0xFF9FF2E9)
val TealOnPrimaryContainerLight = Color(0xFF00201E)
val TealSecondaryLight = Color(0xFF4A635F)
val TealOnSecondaryLight = Color(0xFFFFFFFF)
val TealSecondaryContainerLight = Color(0xFFCCE8E3)
val TealOnSecondaryContainerLight = Color(0xFF05201D)
val CoralTertiaryLight = Color(0xFF984716)
val CoralOnTertiaryLight = Color(0xFFFFFFFF)
val CoralTertiaryContainerLight = Color(0xFFFFDBCA)
val CoralOnTertiaryContainerLight = Color(0xFF351000)
val BackgroundLight = Color(0xFFF4FBF8)
val OnBackgroundLight = Color(0xFF171D1C)
val SurfaceVariantLight = Color(0xFFDAE5E1)
val OnSurfaceVariantLight = Color(0xFF3F4946)
val OutlineLight = Color(0xFF6F7976)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

val TealPrimaryDark = Color(0xFF83D5CC)
val TealOnPrimaryDark = Color(0xFF00372F)
val TealPrimaryContainerDark = Color(0xFF00504B)
val TealOnPrimaryContainerDark = Color(0xFF9FF2E9)
val TealSecondaryDark = Color(0xFFB0CCC7)
val TealOnSecondaryDark = Color(0xFF1C3531)
val TealSecondaryContainerDark = Color(0xFF334B47)
val TealOnSecondaryContainerDark = Color(0xFFCCE8E3)
val CoralTertiaryDark = Color(0xFFFFB68C)
val CoralOnTertiaryDark = Color(0xFF552100)
val CoralTertiaryContainerDark = Color(0xFF763100)
val CoralOnTertiaryContainerDark = Color(0xFFFFDBCA)
val BackgroundDark = Color(0xFF0E1513)
val OnBackgroundDark = Color(0xFFDDE4E1)
val SurfaceVariantDark = Color(0xFF3F4946)
val OnSurfaceVariantDark = Color(0xFFBEC9C5)
val OutlineDark = Color(0xFF889390)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
